spring.application.name=Gestao Juridica

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_juridica
spring.datasource.username=advocacia
spring.datasource.password=advocacia123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Vaadin
vaadin.launch-browser=true